config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "pages/home"
  get "pages/about"
  root to: "pages#home"
  resources :orders
  devise_for :customers

  namespace :api do
    devise_for :customers, defaults: { format: :json },
                           class_name: "ApiCustomer",
                           skip: [:registrations, :invitations,
                                  :passwords, :confirmations,
                                  :unlocks],
                           path: "",
                           path_names: { sign_in: "login",
                                         sign_out: "logout" }
    devise_scope :customer do
      get "login", to: "customers/sessions#new"
      delete "logout", to: "customers/sessions#destroy"
    end
  end
end

app/models/api_customer.rb
class ApiCustomer < Customer
  include Devise::JWT::RevocationStrategies::JTIMatcher
  devise :jwt_authenticatable, jwt_revocation_strategy: self
  validates :jti, presence: true

  def generate_jwt
    JWT.encode({ id: id,
                 exp: 1.day.from_now.to_i },
               Rails.env.devise.jwt.secret_key)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  before_create :add_jti

  def add_jti
    self.jti ||= SecureRandom.uuid
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  enum status: { submitted: "submitted", ready: "ready", filled: "filled" }
end

app/controllers/api/sessions_controller.rb
class Api::SessionsController < Devise::SessionsController
  # I'm guessing this isn't required since we don't track signed in/signed out status for the API user?
  skip_before_action :verify_signed_out_user
  # This sets the default response format to json instead of html
  respond_to :json
  # POST /api/login
  def create
    unless request.format == :json
      sign_out # why is this needed?
      render status: 406,
             json: { message: "JSON requests only." } and return
    end
    # auth_options should have `scope: :api_customer`
    resource = warden.authenticate!(auth_options)
    if resource.blank?
      render status: 401,
             json: { response: "Access denied." } and return
    end
    sign_in(resource_name, resource)
    respond_with resource, location: after_sign_in_path_for(resource) do |format|
      format.json {
        render json: { success: true,
                       jwt: current_token,
                       response: "Authentication successful" }
      }
    end
  end

  private

  def current_token
    request.env["warden-jwt_auth.token"]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, unless: :json_request?
  protect_from_forgery with: :null_session, if: :json_request?
  skip_before_action :verify_authenticity_token, if: :json_request?
  rescue_from ActionController::InvalidAuthenticityToken,
              with: :invalid_auth_token
  before_action :set_current_customer, if: :json_request?

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || orders_path
  end

  private

  def json_request?
    request.format.json?
  end

  # Use api_customer Devise scope for JSON access
  def authenticate_customer!(*args)
    super and return unless args.blank?
    json_request? ? authenticate_api_customer! : super
  end

  def invalid_auth_token
    respond_to do |format|
      format.html {
        redirect_to sign_in_path,
          error: "Login invalid or expired"
      }
      format.json { head 401 }
    end
  end

  # So we can use Pundit policies for api_customers
  def set_current_customer
    @current_customer ||= warden.authenticate(scope: :api_customer)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = current_customer.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = current_customer.orders.find(params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @order.customer = current_customer

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: "Order was successfully created." }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: "Order was successfully updated." }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: "Order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def order_params
    params.require(:order).permit(:item, :quantity, :status)
  end

  # Redirect to orders index page if user tried to access an order that doesn't exist
  # or that they don't have access to
  rescue_from ActiveRecord::RecordNotFound do
    redirect_to orders_url, alert: "Order does not exist."
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWebAndMobile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body>
  <% if customer_signed_in? %>
    <%= link_to("Logout", destroy_customer_session_path, method: :delete) %>        
  <% else %>
    <%= link_to("Login", new_customer_session_path) %>  
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item %>
  </div>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Order.statuses.keys.map { |w| [w.humanize, w] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Quantity</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.item %></td>
        <td><%= order.quantity %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @order.item %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @order.quantity %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
<h1>About</h1>
<p>We are your local cornerstore</p>

app/views/pages/home.html.erb
<h1>Cornerstore</h1>
<p>Place orders with your local cornerstore</p>